### ISSUE TITLE
what is "base" (as in "from base import...")

### ISSUE THREAD

**Issue by polycopter** [elbow-jason/Uno-deprecated#2]

**Comment by polycopter** [comment]
D:\src\py\pyloo\src>python pyloo.py
Traceback (most recent call last):
  File "pyloo.py", line 24, in <module>
    import uno
  File "C:\Python34\lib\site-packages\uno__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: No module named 'base'

D:\src\py\pyloo\src>pip install base
Downloading/unpacking base
  Could not find any downloads that satisfy the requirement base
Cleaning up...
No distributions at all found for base
Storing debug log for failure in C:\Users[redacted]\pip\pip.log

D:\src\py\pyloo\src>

**Comment by polycopter** [comment]
pip install python-base
