### ISSUE TITLE
Cannot import uno in python prompt

### ISSUE THREAD

**Issue by rahulc93** [elbow-jason/Uno-deprecated#4]
```bash
data_mining_env) rahul@rahul-Inspiron-7373:~/code/cqa-data-mining$ pip3 install uno
Processing /home/rahul/.cache/pip/wheels/72/08/5c/1ed0432c2914625261d431dded892518ef1aaa33a371c4d1c8/uno-0.3.3-cp37-none-any.whl
Requirement already satisfied: pytest==2.6.0 in /home/rahul/.virtualenvs/data_mining_env/lib/python3.7/site-packages (from uno) (2.6.0)
Requirement already satisfied: py==1.4.22 in /home/rahul/.virtualenvs/data_mining_env/lib/python3.7/site-packages (from uno) (1.4.22)
Installing collected packages: uno
Successfully installed uno-0.3.3
(data_mining_env) rahul@rahul-Inspiron-7373:~/code/cqa-data-mining$ python3
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rahul/.virtualenvs/data_mining_env/lib/python3.7/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element' from 'base' (/home/rahul/.virtualenvs/data_mining_env/lib/python3.7/site-packages/base/__init__.py)
>>> 
```

**Comment by Wotox** [comment]
Hello, did you solve the problem?
